### ISSUE TITLE
修正依頼

### ISSUE THREAD

**Issue by tatehora** [amemashi/oasispay-wallet#6]
証明書書類をFrontと統一
■日本語
本人確認証明は3つのみ
・運転免許証（表面と裏面） 
・パスポート（顔写真のページ+住所記載のページ）
・個人番号（マイナンバー）カード

住所確認書類
・公共料金の請求書・領収証(電気・都市ガス・水道・NHKのいずれか一つ)
・国税、地方税の領収書または、納税証明書  
・社会保険料の領収書 
・各種健康保険証 
・住民票の写し 

ヘルプを一旦削除

**Comment by amemashi** [comment]
c4ebcf01f2e9a0a1954c52c73db98fef5d7776d6
にて対応

**Comment by tatehora** [comment]
クレカ登録で、セキュリティコードの入力を設ける
